intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

# Public headers.
#
pub = [dir_path] ../include/Zycore/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{zycore}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{zycore}: libul{zycore}: {h c}{**} $impl_libs $intf_libs

# Zycore only defines ZYAN_DLLEXPORT as __declspec(dllexport) when ZYAN_MSVC is
# defined. However, in some cases we may be using a different compiler such as
# Clang on Windows. Here, symbol export will fail because ZYAN_DLLEXPORT remains
# undefined or expands to nothing.
#
# To work around this, we auto export symbols when compiling with Clang on
# Windows.
#
libs{zycore}: def{zycore}: include = ($c.target.system == 'win32-msvc')
              def{zycore}: libul{zycore}

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

c.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc"

if ($c.target.class == 'linux')
  c.poptions += -D_GNU_SOURCE

if ($c.id == 'clang')
  cxx.loptions += -Wl,--export-all-symbols

obja{*}: c.poptions += -DZYCORE_STATIC_BUILD
objs{*}: c.poptions += -DZYCORE_SHOULD_EXPORT

# Export options.
#
lib{zycore}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  c.export.libs = $intf_libs
}

if ($c.target.class != 'windows')
{
  c.libs += -pthread

  lib{zycore}:
  {
    c.export.libs += -pthread
  }
}

liba{zycore}: c.export.poptions += -DZYCORE_STATIC_BUILD
libs{zycore}: c.export.poptions += -DZYCORE_SHOULD_EXPORT

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{zycore}: bin.lib.version = "-$version.project_id"
else
  lib{zycore}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
