intf_libs = # Interface dependencies.
impl_libs = # Implementation dependencies.

# Public headers.
#
pub = [dir_path] ../include/Zycore/

include $pub

pub_hdrs = $($pub/ pub_hdrs)

lib{zycore}: $pub/{$pub_hdrs}

# Private headers and sources as well as dependencies.
#
lib{zycore}: libul{zycore}: {h c}{**} $impl_libs $intf_libs

# Symbol export configuration
#
# On Windows, dynamic libraries require explicit annotation of exported symbols.
# build2 supports two main strategies to automate this, depending on the
# toolchain:
#
# https://build2.org/build2/doc/build2-build-system-manual.xhtml#cc-auto-symexport
#
# 1. MSVC (win32-msvc target): we rely on a definition file (def{}). build2
#    automatically generates the .def export list, which is then passed to the
#    linker. This avoids the need for `__declspec(dllexport)` annotations in the
#    source code.
#
# 2. GNU-style toolchains targeting Windows (MinGW, Clang/LLVM with COFF): we
#    instead request the linker to export all symbols from the object files.
#    This is done by passing `-Wl,--export-all-symbols`.
#
# Note that both approaches are mutually exclusive and selected based on
# `$c.target.system`/`$c.id`. Other platforms ignore this configuration.
#
libs{zycore}: def{zycore}: include = ($c.target.system == 'win32-msvc')
              def{zycore}: libul{zycore}

# Use linker-based automatic export for GNU-style toolchains on Windows
#
if ($c.target.system == 'mingw32' || \
    ($c.target.class == 'windows' && $c.id == 'clang' \
                                  && $c.target.system != 'win32-msvc'))
  c.loptions += -Wl,--export-all-symbols

# Build options.
#
out_pfx_inc = [dir_path] $out_root/include/
src_pfx_inc = [dir_path] $src_root/include/
out_pfx_src = [dir_path] $out_root/src/
src_pfx_src = [dir_path] $src_root/src/

c.poptions =+ "-I$out_pfx_src" "-I$src_pfx_src" \
              "-I$out_pfx_inc" "-I$src_pfx_inc"

if ($c.target.class == 'linux')
  c.poptions += -D_GNU_SOURCE

obja{*}: c.poptions += -DZYCORE_STATIC_BUILD
objs{*}: c.poptions += -DZYCORE_STATIC_BUILD

# Export options.
#
lib{zycore}:
{
  c.export.poptions = "-I$out_pfx_inc" "-I$src_pfx_inc"
  c.export.libs = $intf_libs
}

if ($c.target.class != 'windows')
{
  c.libs += -pthread

  lib{zycore}:
  {
    c.export.libs += -pthread
  }
}

liba{zycore}: c.export.poptions += -DZYCORE_STATIC_BUILD
libs{zycore}: c.export.poptions += -DZYCORE_STATIC_BUILD

# For pre-releases use the complete version to make sure they cannot
# be used in place of another pre-release or the final version. See
# the version module for details on the version.* variable values.
#
if $version.pre_release
  lib{zycore}: bin.lib.version = "-$version.project_id"
else
  lib{zycore}: bin.lib.version = "-$version.major.$version.minor"

# Don't install private headers.
#
h{*}: install = false
